services:
  - type: web
    name: dani-backend-ea0s
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://danielepascoliniphotography_db_user:Fpq24OE8P2muPw3S@qwen35.he7fief.mongodb.net/?appName=QWEN35
      - key: DB_NAME
        value: QWEN35
      - key: PYTHON_VERSION
        value: "3.11"
